pip install altgraph
pip install bdist-mpkg
pip install bonjour-py
pip install cffi
pip install cryptography
pip install cycler
pip install enum34
pip install funcsigs
pip install idna
pip install ipaddress
pip install macholib
pip install matplotlib
pip install mock
pip install modulegraph
pip install ndg-httpsclient
pip install nose
pip install numpy
pip install passlib
pip install pbr
pip install pip
pip install py2app
pip install pyasn1
pip install pycparser
pip install pyobjc-core
pip install pyobjc-framework-Accounts
pip install pyobjc-framework-AddressBook
pip install pyobjc-framework-AppleScriptKit
pip install pyobjc-framework-AppleScriptObjC
pip install pyobjc-framework-Automator
pip install pyobjc-framework-CFNetwork
pip install pyobjc-framework-Cocoa
pip install pyobjc-framework-Collaboration
pip install pyobjc-framework-CoreData
pip install pyobjc-framework-CoreLocation
pip install pyobjc-framework-CoreText
pip install pyobjc-framework-DictionaryServices
pip install pyobjc-framework-EventKit
pip install pyobjc-framework-ExceptionHandling
pip install pyobjc-framework-FSEvents
pip install pyobjc-framework-InputMethodKit
pip install pyobjc-framework-InstallerPlugins
pip install pyobjc-framework-InstantMessage
pip install pyobjc-framework-LatentSemanticMapping
pip install pyobjc-framework-LaunchServices
pip install pyobjc-framework-Message
pip install pyobjc-framework-OpenDirectory
pip install pyobjc-framework-PreferencePanes
pip install pyobjc-framework-PubSub
pip install pyobjc-framework-QTKit
pip install pyobjc-framework-Quartz
pip install pyobjc-framework-ScreenSaver
pip install pyobjc-framework-ScriptingBridge
pip install pyobjc-framework-SearchKit
pip install pyobjc-framework-ServiceManagement
pip install pyobjc-framework-Social
pip install pyobjc-framework-SyncServices
pip install pyobjc-framework-SystemConfiguration
pip install pyobjc-framework-WebKit
pip install pyOpenSSL
pip install pyparsing
pip install python-dateutil
pip install pytz
pip install scipy
pip install setuptools
pip install six
pip install Twisted
pip install vboxapi
pip install xattr
pip install zope.interface
